### ISSUE TITLE
Empty order state after removing an order

### ISSUE THREAD

**Issue by gjunkie** [georgegabe/drive-thru#3]
This one is a bit hard to reproduce, but I'm sometimes getting into a funky state. If you make a few orders back to back, then cancel one of them, you sometimes can get a weird state when clicking to create an order again:
![screen shot 2017-07-18 at 4 40 44 pm](https://user-images.githubusercontent.com/626628/28344426-14d6a47a-6bd8-11e7-8360-37d6a0c8f230.png)

**Comment by gabxgz** [comment]
This one ended up being a CSS issue. The browser was adding some padding to the button that would fire a click event without hitting the link to the order editor.

**Comment by gjunkie** [comment]
This was fixed 👍
